version: "2"

services:
  postgres: 
    container_name: postgres_container
    image: postgres
    environment: 
      POSTGRES_USER: ${PGUSER}
      POSTGRES_DB: ${PGDATABASE}
      POSTGRES_PASSWORD: ${PGPASSWORD}
    restart: unless-stopped 
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - 5432:5432
    networks: 
      - postgres
  backend:
    container_name: backend_container
    build:
      context: ./
    restart: always
    networks: 
      - postgres
    depends_on:
      postgres: 
        condition: service_healthy

networks:
  postgres:
    driver: bridge